---
# tasks file for backend
- name: Make sure the backend user exists
  become: true
  user:
    name: "{{ backend_user }}"
- name: Create a directory if it doesn't exist
  become: true
  ansible.builtin.file:
    path: /home/{{ backend_user }}
    state: directory
    owner: "{{ backend_user }}"
    mode: '0755'
- name: Make sure the acl, git is installend
  become: true
  package:
    name: acl
    state: present
- name: Make sure the git repository is cloned and up to date
  become: true
  become_user: "{{ backend_user }}"
  git:
    repo: https://github.com/bezkoder/nodejs-express-sequelize-mysql.git
    force: yes
    dest: /home/{{ backend_user }}/backendmysql
- name: Install packages for the backend app
  become: true
  become_user: "{{ backend_user }}"
  community.general.npm:
    path: /home/{{ backend_user }}/backendmysql
- name: Make sure DB config is updated
  become: true
  template:
    src: db.config.js.j2
    dest: /home/{{ backend_user }}/backendmysql/app/config/db.config.js
- name: Provision the unit file
  become: true
  template:
    src: tutorials.service.j2
    dest: /etc/systemd/system/tutorials.service
- name: Refresh systemd
  become: true
  systemd:
    daemon_reload: yes
    name: tutorials
    state: started
- name: Restart tutorials.service 
  become: true
  systemd:
    name: tutorials
    state: restarted


