---
- name: Gather information about VPCs
  amazon.aws.ec2_vpc_net_info:
    filters:
      "tag:Name": "{{ AWS_PREFIX }}_VPC"
  register: aws_vpc_info
- name: Gather information about subnets
  amazon.aws.ec2_vpc_subnet_info:
    filters:
      vpc-id: "{{ aws_vpc_info.vpcs[0].vpc_id }}"
      "tag:Name": "{{ AWS_PREFIX }}_SUBNET"
  when: aws_vpc_info.vpcs | length > 0
  register: aws_subnet_info
- name: Gather info about the Internet gateway
  community.aws.ec2_vpc_igw_info:
    filters:
      "tag:Name": "{{ AWS_PREFIX }}_IGW"
      attachment.vpc-id: "{{ aws_vpc_info.vpcs[0].vpc_id }}"
  when: aws_vpc_info.vpcs | length
  register: aws_igw_info
- name: Gather info about the routing table
  community.aws.ec2_vpc_route_table_info:
    filters:
      "tag:Name": "{{ AWS_PREFIX }}_RTBL"
      association.subnet-id: "{{ aws_subnet_info.subnets[0].subnet_id }}"
  when: aws_subnet_info is defined and aws_subnet_info.subnets | length > 0
  register: aws_route_info
- name: Gather info about the security group
  amazon.aws.ec2_group_info:
    filters:
      group-name: "{{ AWS_PREFIX }}_SECGRP"
      vpc_id: "{{ aws_vpc_info.vpcs[0].vpc_id }}"
  when: aws_vpc_info.vpcs | length > 0
  register: aws_group_info
- name: Gather info about the EC2 instance(s)
  community.aws.ec2_instance_info:
    filters:
      "tag:Name": "{{ AWS_PREFIX }}_EC2"
      instance-state-name: running
  register: aws_ec2_info
- name: Terminating instance
  community.aws.ec2_instance:
    state: terminated
    instance_ids: 
      - "{{ aws_ec2_info.instances[0].instance_id }}"
- name: Remove sec group
  ec2_group:
    region: us-west-2
    group_id: "{{  aws_group_info.security_groups[0].group_id }}"
    state: absent
- name: Remove IGW
  ec2_vpc_igw:
    state: absent
    vpc_id: "{{ aws_vpc_info.vpcs[0].vpc_id }}"
- name: Remove subnet
  ec2_vpc_subnet:
    state: absent
    vpc_id: "{{ aws_vpc_info.vpcs[0].vpc_id }}"
    cidr: 10.100.10.0/24
- name: Remove Routing table
  ec2_vpc_route_table:
    vpc_id: "{{ aws_vpc_info.vpcs[0].vpc_id }}"
    region: us-west-2
    route_table_id: "{{ aws_route_info.route_tables[0].route_table_id }}"
    lookup: id
    state: absent
- name: Remove VPC 
  ec2_vpc_net:
    name: "{{ AWS_PREFIX }}_VPC"
    cidr_block: 10.100.0.0/16
    state: absent
    purge_cidrs: yes 

- name: Refresh the inventory
  meta: refresh_inventory
